version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.7.1.3-3
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            # - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
        volumes:
            - ../../dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
            - mysql
        volumes:
            # - ./requirements.txt:/requirements.txt:ro
            - ../../dags:/usr/local/airflow/dags
            - ./_data:/data
        environment:
            - LOAD_EX=n
            # - FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EXECUTOR=Local
        command: scheduler -n 5

    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_DATABASE=main
        ports:
          - "3306:3306"
        volumes:
          - ./_mysql:/var/lib/mysql
